version: 2.1

jobs:
  test:
    docker:
      # Usamos una imagen Docker con Python preinstalado
      - image: circleci/python:3.9
    steps:
      # 1. Checkout del código
      - checkout
      # 2. Configurar entorno
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      # 3. Ejecutar pruebas
      - run:
          name: Run tests
          command: pytest --disable-warnings

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
